// constant for course
export const GET_COURSE_LIST = "GET_COURSE_LIST";
export const GET_CATALOG_LIST = "GET_CATALOG_LIST";
export const GET_COURSE_LIST_BY_CATALOG = "GET_COURSE_LIST_BY_CATALOG";
export const GET_COURSE_LIST_BY_PAGINATION = "GET_COURSE_LIST_BY_PAGINATION";
