// constant for course
export const GET_COURSE_LIST = "GET_COURSE_LIST";
export const GET_CATALOG_LIST = "GET_CATALOG_LIST";
export const GET_COURSE_LIST_BY_CATALOG = "GET_COURSE_LIST_BY_CATALOG";
export const GET_INFOR_COURSE = "GET_INFOR_COURSE";
export const GET_COURSE_LIST_BY_PAGINATION = "GET_COURSE_LIST_BY_PAGINATION";
export const GET_COURSE_INFORMATION = "GET_COURSE_INFORMATION";
export const GET_STUDENT_INFORMATION_OF_COURSE =
  "GET_STUDENT_INFORMATION_OF_COURSE";
// constant for user
export const GET_USER_TYPE_LIST = "GET_USER_TYPE_LIST";
export const LOG_IN = "LOG_IN";
export const REGISTER_USER = "REGISTER_USER";
export const GET_USER_LIST = "GET_USER_LIST";
export const GET_USER_LIST_BY_PAGINATION = "GET_USER_LIST_BY_PAGINATION";
export const GET_SEARCH_USER = "GET_SEARCH_USER";
export const ACCOUNT_INFORMATION = "ACCOUNT_INFORMATION";
export const ADD_USER = "ADD_USER";
export const UPDATE_USER = "UPDATE_USER";
export const DELETE_USER = "DELETE_USER";
export const GET_UNREGISTER_COURSE_LIST = "GET_UNREGISTER_COURSE_LIST";
export const GET_COURSE_LIST_PENDING_REVIEW = "GET_COURSE_LIST_PENDING_REVIEW";
export const GET_COURSE_LIST_APPROVED = "GET_COURSE_LIST_APPROVED";
export const GET_USER_LIST_UNREGISTER = "GET_USER_LIST_UNREGISTER";
export const GET_USER_LIST_PENDING_REVIEW = "GET_USER_LIST_PENDING_REVIEW";
export const GET_USER_LIST_OF_COURSE = "GET_USER_LIST_OF_COURSE";
